/* Harris Portfolio intro — tracer-driven erasure reveal. */
(()=>{'use strict';
const overlay=document.getElementById('portfolio-entry-overlay');if(!overlay)return;
const root=document.documentElement;
const nav=performance.getEntriesByType?.('navigation')?.[0];
const fullEffects=root.dataset.effects==='full';
const skip=nav?.type==='back_forward'||window.matchMedia?.('(forced-colors: active)').matches||(!fullEffects&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches);
const finishImmediately=()=>{overlay.replaceChildren();overlay.remove();root.dataset.entryState='complete';};if(skip){finishImmediately();return;}
const WHITE_HOLD_MS=300,EFFECT_DURATION_MS=3200,TOTAL_MS=WHITE_HOLD_MS+EFFECT_DURATION_MS,SPAWN_CUTOFF_MS=1450,EFFECT_BRIDGE_FADE_START_MS=2450,FAILSAFE_MS=4900,MAX_CANVAS_PIXELS=8500000;
const TEAL_RELEASE={immediateShare:.055,earlyShare:.20,earlyEnd:360,midShare:.50,midEnd:980};
const COVERAGE_SECONDARY={startMin:1180,startMax:2050};
const GOLD_WAVE={lineMin:4,lineMax:6,nodeMin:7,nodeMax:11,minVisible:.10};
const COLORS={darkTeal:'#06151c',tealDark:'#0b4d50',tealGreen:'#1a7f77',tealBright:'#63d5d0',tealWhite:'#edf7f8',gold:'#d8b86a',goldHi:'#fff0b0'};
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const easeInOut=t=>{t=clamp(t,0,1);return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;};const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
function chooseTealStart(){const r=Math.random();if(r<TEAL_RELEASE.immediateShare)return rand(0,28);if(r<TEAL_RELEASE.earlyShare)return rand(28,TEAL_RELEASE.earlyEnd);if(r<TEAL_RELEASE.midShare)return rand(TEAL_RELEASE.earlyEnd,TEAL_RELEASE.midEnd);return rand(TEAL_RELEASE.midEnd,SPAWN_CUTOFF_MS);}
const tealLayer=document.createElement('div');tealLayer.className='entry-teal-layer';tealLayer.setAttribute('aria-hidden','true');const mask=document.createElement('canvas');mask.className='entry-mask-canvas';mask.setAttribute('aria-hidden','true');const fx=document.createElement('canvas');fx.className='entry-fx-canvas';fx.setAttribute('aria-hidden','true');overlay.append(tealLayer,mask,fx);
const mctx=mask.getContext('2d',{alpha:true}),fctx=fx.getContext('2d',{alpha:true});if(!mctx||!fctx){finishImmediately();return;}
let cssW=1,cssH=1,dpr=1,start=0,raf=0,watchdog=0,finished=false,tealEvents=[],goldEvents=[];
let initialViewportW=0,initialViewportH=0,hiddenAt=0,lastElapsed=0;
function resizeCanvas(c,ctx){c.width=Math.max(1,Math.round(cssW*dpr));c.height=Math.max(1,Math.round(cssH*dpr));c.style.width=`${cssW}px`;c.style.height=`${cssH}px`;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;}
function chooseCanvasDpr(){const device=Math.min(window.devicePixelRatio||1,3),budget=Math.sqrt(MAX_CANVAS_PIXELS/Math.max(1,cssW*cssH));return Math.max(1,Math.min(device,budget));}
function chooseSpeedVwPerMs(){const r=Math.random();if(r<.22)return rand(.015,.023);if(r<.92)return rand(.009,.015);return rand(.006,.009);}
function chooseFamily(){const r=Math.random();if(r<.42)return{color:COLORS.tealDark,rgb:'11,77,80'};if(r<.84)return{color:COLORS.tealGreen,rgb:'26,127,119'};return{color:COLORS.tealBright,rgb:'99,213,208'};}
function makeParticle(o={}){const thickness=o.thickness??(Math.random()<.84?rand(.55,2.1):rand(2.1,3)),family=chooseFamily(),speedVwMs=o.speedVwMs??chooseSpeedVwPerMs();return{y:o.y??rand(.5,Math.max(1,cssH-.5)),thickness,headLen:o.headLen??rand(2.5,13),tracerLen:o.tracerLen??rand(2.6,3.6)*cssW,dir:o.dir??(Math.random()<.5?1:-1),start:o.start??chooseTealStart(),speedPxMs:speedVwMs*cssW,preRollMs:o.preRollMs??rand(40,140),color:family.color,rgb:family.rgb,intensity:o.intensity??rand(.52,1),glowPct:o.glowPct??rand(.04,.20),glowIntensity:o.glowIntensity??rand(0,1),glowIntensity2:o.glowIntensity2??rand(0,1),eraseWidth:o.eraseWidth??Math.max(1,thickness*rand(.95,1.6)),coverage:!!o.coverage,coveragePass:o.coveragePass??0,coverageTop:o.coverageTop??null,coverageHeight:o.coverageHeight??null,completed:false};}
function makeCoverageStrips(overlap=1.2){const stripH=clamp(cssH/96,3.5,8),strips=[];for(let top=0;top<cssH;top+=stripH){const rawHeight=Math.min(stripH+overlap,cssH-top),coverageTop=Math.max(0,top-overlap*.5),coverageBottom=Math.min(cssH,top+rawHeight+overlap*.5),coverageHeight=Math.max(0,coverageBottom-coverageTop);strips.push({top:coverageTop,height:coverageHeight,y:clamp(top+stripH*.5+rand(-stripH*.16,stripH*.16),.5,cssH-.5)});}return strips;}
function buildPrimaryCoveragePass(){const strips=shuffle(makeCoverageStrips(1.2));let cursor=0,clusterIndex=0;const clusterTotal=Math.ceil(strips.length/7);while(cursor<strips.length){const remaining=strips.length-cursor,members=Math.min(remaining,Math.round(rand(4,9))),progress=clusterTotal<=1?0:clusterIndex/Math.max(1,clusterTotal-1),releaseCurve=Math.pow(progress,.82),baseStart=releaseCurve*1260+rand(-45,75),baseSpeed=rand(.0115,.0175),baseDir=Math.random()<.5?1:-1,basePreRoll=rand(55,125);for(let j=0;j<members;j++){const s=strips[cursor+j],dir=Math.random()<.84?baseDir:-baseDir;tealEvents.push(makeParticle({y:s.y,dir,start:clamp(baseStart+rand(-45,85),0,1360),speedVwMs:baseSpeed*rand(.92,1.10),preRollMs:basePreRoll+rand(-20,25),tracerLen:rand(3.1,4.1)*cssW,thickness:rand(.65,1.8),eraseWidth:s.height,intensity:rand(.48,.84),coverage:true,coveragePass:1,coverageTop:s.top,coverageHeight:s.height}));}cursor+=members;clusterIndex++;}}
function buildSecondaryCoveragePass(){const strips=shuffle(makeCoverageStrips(1.8));let cursor=0;while(cursor<strips.length){const members=Math.min(strips.length-cursor,Math.round(rand(3,7))),baseStart=rand(COVERAGE_SECONDARY.startMin,COVERAGE_SECONDARY.startMax),baseDir=Math.random()<.5?1:-1,baseSpeed=rand(.0125,.019),basePreRoll=rand(65,135);for(let j=0;j<members;j++){const s=strips[cursor+j],dir=Math.random()<.72?baseDir:-baseDir;tealEvents.push(makeParticle({y:s.y,dir,start:clamp(baseStart+rand(-70,90),COVERAGE_SECONDARY.startMin,EFFECT_BRIDGE_FADE_START_MS-160),speedVwMs:baseSpeed*rand(.94,1.12),preRollMs:basePreRoll+rand(-18,24),tracerLen:rand(3.3,4.3)*cssW,thickness:rand(.60,1.65),eraseWidth:s.height,intensity:rand(.44,.76),coverage:true,coveragePass:2,coverageTop:s.top,coverageHeight:s.height}));}cursor+=members;}}
function makeGoldNodes(count){const nodes=[];for(let i=0;i<count;i++){const x=(i+.5+rand(-.28,.28))/count;nodes.push({x:clamp(x,.035,.965),width:rand(.025,.11),phase:rand(0,Math.PI*2),speed:rand(.00125,.00305),amp:rand(.46,1),floor:rand(.02,.16),drift:Math.random()<.28?rand(.018,.065):rand(.002,.018),driftSpeed:rand(.00055,.00155),driftPhase:rand(0,Math.PI*2),hotspot:rand(.55,1),erase:rand(.65,1)});}return nodes;}
function buildEvents(){tealEvents=[];goldEvents=[];const independentCount=Math.round(rand(184,276));for(let i=0;i<independentCount;i++)tealEvents.push(makeParticle());const clusterCount=Math.round(rand(10,18));for(let c=0;c<clusterCount;c++){const members=Math.round(rand(4,9)),dir=Math.random()<.5?1:-1,baseY=rand(cssH*.05,cssH*.95),baseStart=chooseTealStart(),baseSpeed=chooseSpeedVwPerMs(),basePreRoll=rand(45,125),spread=rand(5,28);for(let j=0;j<members;j++)tealEvents.push(makeParticle({y:clamp(baseY+rand(-spread,spread),.5,cssH-.5),dir,start:clamp(baseStart+rand(-28,52),0,SPAWN_CUTOFF_MS),speedVwMs:baseSpeed*rand(.92,1.08),preRollMs:basePreRoll+rand(-18,18),tracerLen:rand(3,4)*cssW,intensity:rand(.64,1)}));}buildPrimaryCoveragePass();buildSecondaryCoveragePass();const goldCount=Math.round(rand(GOLD_WAVE.lineMin,GOLD_WAVE.lineMax));for(let i=0;i<goldCount;i++){const goldStart=rand(0,150),nodeCount=Math.round(rand(GOLD_WAVE.nodeMin,GOLD_WAVE.nodeMax));goldEvents.push({y:rand(cssH*.08,cssH*.92),thickness:rand(10,17),start:goldStart,duration:EFFECT_DURATION_MS-goldStart,phase:rand(0,Math.PI*2),metalAlpha:rand(.13,.24),roughness:rand(.75,1.35),waveSpeed:rand(.0010,.0018),waveSpan:rand(3.5,6.5),bloom:rand(.75,1.15),nodes:makeGoldNodes(nodeCount)});}}
function resetWhite(){mctx.globalCompositeOperation='source-over';mctx.globalAlpha=1;mctx.fillStyle='#fff';mctx.fillRect(0,0,cssW,cssH);}
function initializeViewport(){cssW=Math.max(1,window.innerWidth);cssH=Math.max(1,window.innerHeight);dpr=chooseCanvasDpr();initialViewportW=cssW;initialViewportH=cssH;resizeCanvas(mask,mctx);resizeCanvas(fx,fctx);tealLayer.style.background=COLORS.darkTeal;tealLayer.style.opacity='1';resetWhite();buildEvents();overlay.style.background='transparent';}
function eraseRect(x,y,w,h,a=1){if(w<=0||h<=0)return;mctx.save();mctx.globalCompositeOperation='destination-out';mctx.globalAlpha=a;mctx.fillStyle='#000';mctx.fillRect(x,y,w,h);mctx.restore();}
function eraseVisibleTracer(e,tailStart,head){const eraseTail=e.coverage?tailStart:tailStart+e.dir*(e.tracerLen*.02),left=clamp(Math.min(eraseTail,head),0,cssW),right=clamp(Math.max(eraseTail,head),0,cssW);if(right<=left)return;if(e.coverage&&e.coverageTop!==null&&e.coverageHeight!==null)eraseRect(left,e.coverageTop,right-left,e.coverageHeight,1);else eraseRect(left,e.y-e.eraseWidth/2,right-left,e.eraseWidth,1);}
function markCoverageComplete(e){if(e.coverage)e.completed=true;}
function makeTracerGradient(e,tailStart,head,mode){const g=fctx.createLinearGradient(tailStart,0,head,0);if(mode==='halo2'){g.addColorStop(0,`rgba(${e.rgb},0)`);g.addColorStop(.10,`rgba(${e.rgb},.38)`);g.addColorStop(.92,`rgba(${e.rgb},.38)`);g.addColorStop(1,'rgba(99,213,208,.48)');}else if(mode==='halo1'){g.addColorStop(0,`rgba(${e.rgb},0)`);g.addColorStop(.10,`rgba(${e.rgb},.56)`);g.addColorStop(.92,`rgba(${e.rgb},.56)`);g.addColorStop(1,'rgba(99,213,208,.68)');}else{g.addColorStop(0,'rgba(6,21,28,0)');g.addColorStop(.008,`rgba(${e.rgb},.18)`);g.addColorStop(.02,`rgba(${e.rgb},.64)`);g.addColorStop(.20,`rgba(${e.rgb},.66)`);g.addColorStop(.50,`rgba(${e.rgb},.68)`);g.addColorStop(.80,`rgba(${e.rgb},.70)`);g.addColorStop(.94,`rgba(${e.rgb},.74)`);g.addColorStop(.98,'rgba(99,213,208,.86)');g.addColorStop(.995,'rgba(99,213,208,.97)');g.addColorStop(1,'rgba(237,247,248,1)');}return g;}
function drawTracerStroke(e,tailStart,head){const coreGradient=makeTracerGradient(e,tailStart,head,'core'),halo1Gradient=makeTracerGradient(e,tailStart,head,'halo1'),halo2Gradient=makeTracerGradient(e,tailStart,head,'halo2'),primaryRadius=Math.max(6.6,e.thickness*(3+e.glowPct*18)),secondaryRadius=Math.max(10,primaryRadius*1.5),primaryWidth=e.thickness+3*Math.max(.8,e.thickness*e.glowPct*2.5),secondaryWidth=e.thickness+2*Math.max(1.8,e.thickness*e.glowPct*5);fctx.save();fctx.lineCap='butt';fctx.globalAlpha=e.intensity*e.glowIntensity2;fctx.strokeStyle=halo2Gradient;fctx.lineWidth=secondaryWidth;fctx.shadowColor=e.color;fctx.shadowBlur=secondaryRadius;fctx.beginPath();fctx.moveTo(tailStart,e.y);fctx.lineTo(head,e.y);fctx.stroke();fctx.globalAlpha=e.intensity*e.glowIntensity;fctx.strokeStyle=halo1Gradient;fctx.lineWidth=primaryWidth;fctx.shadowBlur=primaryRadius;fctx.beginPath();fctx.moveTo(tailStart,e.y);fctx.lineTo(head,e.y);fctx.stroke();fctx.shadowBlur=0;fctx.globalAlpha=e.intensity*.34;fctx.strokeStyle=coreGradient;fctx.lineWidth=Math.max(.5,e.thickness*1.18);fctx.beginPath();fctx.moveTo(tailStart,e.y);fctx.lineTo(head,e.y);fctx.stroke();fctx.globalAlpha=e.intensity;fctx.lineWidth=Math.max(.45,e.thickness*.82);fctx.beginPath();fctx.moveTo(tailStart,e.y);fctx.lineTo(head,e.y);fctx.stroke();fctx.restore();return{primaryRadius,secondaryRadius};}
function drawTealEvent(e,t){const elapsed=t-e.start;if(elapsed<0)return false;const pad=Math.max(24,e.headLen*2),startX=e.dir>0?-pad:cssW+pad,head=startX+e.dir*e.speedPxMs*(elapsed+e.preRollMs),tailStart=head-e.dir*e.tracerLen,tailGone=e.dir>0?tailStart>cssW+pad:tailStart<-pad;if(tailGone){markCoverageComplete(e);return false;}const primaryRadius=Math.max(6.6,e.thickness*(3+e.glowPct*18)),secondaryRadius=Math.max(10,primaryRadius*1.5),visualPad=secondaryRadius+Math.max(4,e.thickness*6),segmentLeft=Math.min(tailStart,head),segmentRight=Math.max(tailStart,head),segmentVisible=segmentRight>=-visualPad&&segmentLeft<=cssW+visualPad;if(!segmentVisible)return true;eraseVisibleTracer(e,tailStart,head);const halo=drawTracerStroke(e,tailStart,head),headOnOrNearScreen=head>=-pad&&head<=cssW+pad;if(headOnOrNearScreen){const headX=e.dir>0?head-e.headLen:head,hg=fctx.createLinearGradient(headX,0,headX+e.headLen,0);if(e.dir>0){hg.addColorStop(0,'rgba(99,213,208,.12)');hg.addColorStop(.58,e.color);hg.addColorStop(.88,COLORS.tealBright);hg.addColorStop(1,COLORS.tealWhite);}else{hg.addColorStop(0,COLORS.tealWhite);hg.addColorStop(.12,COLORS.tealBright);hg.addColorStop(.42,e.color);hg.addColorStop(1,'rgba(99,213,208,.12)');}fctx.save();fctx.fillStyle=e.color;fctx.shadowColor=e.color;fctx.shadowBlur=halo.secondaryRadius;fctx.globalAlpha=e.intensity*e.glowIntensity2*.72;fctx.fillRect(headX,e.y-e.thickness/2,e.headLen,e.thickness);fctx.shadowBlur=halo.primaryRadius;fctx.globalAlpha=e.intensity*e.glowIntensity*.86;fctx.fillRect(headX,e.y-e.thickness/2,e.headLen,e.thickness);fctx.shadowBlur=0;fctx.globalAlpha=e.intensity;fctx.fillStyle=hg;fctx.fillRect(headX,e.y-e.thickness/2,e.headLen,e.thickness);const coreW=Math.max(1,Math.min(3.2,e.headLen*.2)),coreX=e.dir>0?head-coreW:head,coreH=Math.max(.45,Math.min(1.2,e.thickness*.68));fctx.globalAlpha=Math.min(1,e.intensity+.22);fctx.fillStyle=COLORS.tealWhite;fctx.fillRect(coreX,e.y-coreH/2,coreW,coreH);fctx.restore();}return true;}

/* Gold line: anchored metallic edge with phase-coupled oscillating glint nodes. */
function drawGoldEvent(e,t){const local=(t-e.start)/e.duration;if(local<0||local>1)return false;const envelope=Math.min(1,local/.10,(1-local)/.08),life=clamp(envelope,0,1);if(life<=0)return false;
  fctx.save();fctx.lineCap='round';
  const metalPulse=.90+.10*Math.sin(t*.0022*e.roughness+e.phase);fctx.globalAlpha=e.metalAlpha*metalPulse*life;fctx.strokeStyle='rgba(216,184,106,.86)';fctx.lineWidth=Math.max(1.2,e.thickness*.18);fctx.beginPath();fctx.moveTo(0,e.y);fctx.lineTo(cssW,e.y);fctx.stroke();
  const finePulse=.76+.24*Math.sin(t*.0031*e.roughness+e.phase*1.37);fctx.globalAlpha=e.metalAlpha*.58*finePulse*life;fctx.strokeStyle='rgba(255,224,150,.76)';fctx.lineWidth=Math.max(.7,e.thickness*.075);fctx.beginPath();fctx.moveTo(0,e.y);fctx.lineTo(cssW,e.y);fctx.stroke();
  fctx.globalCompositeOperation='lighter';
  const wavePhase=t*e.waveSpeed+e.phase;
  for(const n of e.nodes){const coupled=wavePhase+n.x*e.waveSpan,osc=.5+.5*Math.sin(t*n.speed+n.phase+coupled),secondary=.5+.5*Math.sin(t*n.speed*.61+n.phase*1.73-coupled*.42),intensity=clamp(n.floor+n.amp*(osc*.78+secondary*.22),0,1)*life;if(intensity<GOLD_WAVE.minVisible)continue;
    const driftPx=n.drift*cssW*Math.sin(t*n.driftSpeed+n.driftPhase),center=clamp(n.x*cssW+driftPx,0,cssW),width=clamp(n.width*cssW*(.68+.62*intensity),6,cssW*.15),half=width*.5,x0=Math.max(0,center-half),x1=Math.min(cssW,center+half);if(x1<=x0)continue;
    const eraseWidth=Math.max(1,e.thickness*(.34+.48*intensity));eraseRect(x0,e.y-eraseWidth/2,x1-x0,eraseWidth,clamp(intensity*n.erase*.92,.18,1));
    const shoulder=fctx.createLinearGradient(x0,0,x1,0);shoulder.addColorStop(0,'rgba(216,184,106,0)');shoulder.addColorStop(.20,'rgba(216,184,106,.12)');shoulder.addColorStop(.42,'rgba(255,221,132,.42)');shoulder.addColorStop(.5,'rgba(255,240,176,.68)');shoulder.addColorStop(.58,'rgba(255,221,132,.42)');shoulder.addColorStop(.80,'rgba(216,184,106,.12)');shoulder.addColorStop(1,'rgba(216,184,106,0)');fctx.globalAlpha=intensity*.88;fctx.strokeStyle=shoulder;fctx.lineWidth=Math.max(1,e.thickness*(.22+.20*intensity));fctx.shadowColor=COLORS.gold;fctx.shadowBlur=Math.max(2,e.thickness*(.42+.38*intensity))*e.bloom;fctx.beginPath();fctx.moveTo(x0,e.y);fctx.lineTo(x1,e.y);fctx.stroke();
    const specHalf=Math.max(3,width*(.09+.09*n.hotspot)),s0=Math.max(0,center-specHalf),s1=Math.min(cssW,center+specHalf),spec=fctx.createLinearGradient(s0,0,s1,0);spec.addColorStop(0,'rgba(255,226,145,0)');spec.addColorStop(.30,'rgba(255,235,172,.34)');spec.addColorStop(.46,'rgba(255,249,218,.88)');spec.addColorStop(.50,'rgba(255,255,248,1)');spec.addColorStop(.54,'rgba(255,249,218,.88)');spec.addColorStop(.70,'rgba(255,235,172,.34)');spec.addColorStop(1,'rgba(255,226,145,0)');fctx.globalAlpha=clamp(intensity*(.62+.50*n.hotspot),0,1);fctx.strokeStyle=spec;fctx.lineWidth=Math.max(.75,e.thickness*(.09+.11*intensity));fctx.shadowColor=COLORS.goldHi;fctx.shadowBlur=Math.max(2,e.thickness*(.48+.42*intensity))*e.bloom;fctx.beginPath();fctx.moveTo(s0,e.y);fctx.lineTo(s1,e.y);fctx.stroke();
  }
  fctx.restore();return true;}
function allCoverageComplete(){for(const e of tealEvents)if(e.coverage&&!e.completed)return false;return true;}
function detachLifecycleListeners(){window.removeEventListener('resize',handleViewportChange);window.removeEventListener('pageshow',handlePageShow);document.removeEventListener('visibilitychange',handleVisibilityChange);}
function cleanupRenderResources(){try{fctx.clearRect(0,0,cssW,cssH);mctx.clearRect(0,0,cssW,cssH);}catch(_){}tealEvents.length=0;goldEvents.length=0;mask.width=1;mask.height=1;fx.width=1;fx.height=1;overlay.replaceChildren();}
function finish(){if(finished)return;finished=true;clearTimeout(watchdog);watchdog=0;if(raf)cancelAnimationFrame(raf);raf=0;detachLifecycleListeners();cleanupRenderResources();overlay.remove();root.dataset.entryState='complete';}
function frame(now){if(finished||document.hidden)return;if(!start)start=now;const elapsed=now-start;lastElapsed=elapsed;fctx.clearRect(0,0,cssW,cssH);if(elapsed<WHITE_HOLD_MS){raf=requestAnimationFrame(frame);return;}const effectTime=elapsed-WHITE_HOLD_MS;let goldActive=false;for(const e of goldEvents)if(drawGoldEvent(e,effectTime))goldActive=true;for(const e of tealEvents)drawTealEvent(e,effectTime);const coverageComplete=allCoverageComplete();if(effectTime>=EFFECT_BRIDGE_FADE_START_MS&&coverageComplete){const p=clamp((effectTime-EFFECT_BRIDGE_FADE_START_MS)/(EFFECT_DURATION_MS-EFFECT_BRIDGE_FADE_START_MS),0,1);tealLayer.style.opacity=String(1-easeInOut(p));}if(effectTime>=EFFECT_DURATION_MS&&coverageComplete&&!goldActive){finish();return;}raf=requestAnimationFrame(frame);}
function handleViewportChange(){if(finished)return;const width=Math.max(1,window.innerWidth),height=Math.max(1,window.innerHeight);const widthDelta=Math.abs(width-initialViewportW)/Math.max(1,initialViewportW);const orientationFlip=(width>height)!==(initialViewportW>initialViewportH);if(orientationFlip||widthDelta>.25)finish();}
function handlePageShow(event){if(event.persisted)finish();}
function armWatchdog(){clearTimeout(watchdog);const remaining=Math.max(250,FAILSAFE_MS-lastElapsed);watchdog=setTimeout(finish,remaining);}
function handleVisibilityChange(){if(finished)return;if(document.hidden){hiddenAt=performance.now();clearTimeout(watchdog);watchdog=0;if(raf)cancelAnimationFrame(raf);raf=0;return;}if(hiddenAt){const now=performance.now();if(start)start+=now-hiddenAt;hiddenAt=0;}armWatchdog();if(!raf)raf=requestAnimationFrame(frame);}
try{initializeViewport();root.dataset.entryState='running';window.addEventListener('resize',handleViewportChange,{passive:true});window.addEventListener('pageshow',handlePageShow,{passive:true});document.addEventListener('visibilitychange',handleVisibilityChange,{passive:true});if(document.hidden){hiddenAt=performance.now();}else{armWatchdog();raf=requestAnimationFrame(frame);}}catch(error){console.error('Entry overlay failed safely:',error);finishImmediately();}
})();