/* Harris Portfolio intro — optimized tracer-driven erasure reveal. */
(()=>{'use strict';
const overlay=document.getElementById('portfolio-entry-overlay');if(!overlay)return;
const root=document.documentElement;
const nav=performance.getEntriesByType?.('navigation')?.[0];
const fullEffects=root.dataset.effects==='full';
const skip=nav?.type==='back_forward'||window.matchMedia?.('(forced-colors: active)').matches||(!fullEffects&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches);
const finishImmediately=()=>{overlay.replaceChildren();overlay.remove();root.dataset.entryState='complete';};if(skip){finishImmediately();return;}

const WHITE_HOLD_MS=300,EFFECT_DURATION_MS=3200,SPAWN_CUTOFF_MS=1450,EFFECT_BRIDGE_FADE_START_MS=2450,FAILSAFE_MS=4900;
const GOLD_BLOOM_WINDOW_START_MS=1180,GOLD_BLOOM_WINDOW_END_MS=2040;
const GOLD_DIM_START_MS=2050,GOLD_DIM_END_MS=2375;
const MAX_DPR=2,MAX_CANVAS_PIXELS=4500000;
const TEAL_RELEASE={immediateShare:.055,earlyShare:.20,earlyEnd:360,midShare:.50,midEnd:980};
const COVERAGE_SECONDARY={startMin:1180,startMax:2050};
const GOLD_WAVE={lineMin:4,lineMax:6,nodeMin:5,nodeMax:8,minVisible:.12,travelerMin:1,travelerMax:2};
const COLORS={darkTeal:'#06151c',tealDark:'#0b4d50',tealGreen:'#1a7f77',tealBright:'#63d5d0',tealWhite:'#edf7f8',gold:'#d8b86a',goldHi:'#fff0b0',goldRidge:'#e8b843'};
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const biasedHigh=(a,b,p=.34)=>a+(b-a)*Math.pow(Math.random(),p);
const easeInOut=t=>{t=clamp(t,0,1);return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;};
const smoothstep=t=>{t=clamp(t,0,1);return t*t*(3-2*t);};
const singleBloomPulse=(t,start,peak,end,hero=false)=>{if(t<=start||t>=end)return 0;const halfPlateau=hero?clamp((end-start)*.13,22,36):clamp((end-start)*.09,12,22),p0=Math.max(start,peak-halfPlateau),p1=Math.min(end,peak+halfPlateau);if(t>=p0&&t<=p1)return 1;if(t<p0)return smoothstep((t-start)/Math.max(1,p0-start));return 1-smoothstep((t-p1)/Math.max(1,end-p1));};
const goldBloomEnvelope=(t,b)=>{if(!b?.bloom||t<=b.bloomStart||t>=b.bloomEnd)return 0;if(b.hero||!b.bloomRepeats||b.bloomRepeats<=1)return singleBloomPulse(t,b.bloomStart,b.bloomPeak,b.bloomEnd,b.hero);const count=Math.min(3,b.bloomRepeats),span=b.bloomEnd-b.bloomStart,slot=span/count;let out=0;for(let i=0;i<count;i++){const center=b.bloomStart+slot*(i+.5),half=slot*.42,amp=i===0?1:i===1?.84:.70;out=Math.max(out,singleBloomPulse(t,center-half,center,center+half,false)*amp);}return out;};
const goldExitGain=t=>t<=GOLD_DIM_START_MS?1:t>=GOLD_DIM_END_MS?0:1-smoothstep((t-GOLD_DIM_START_MS)/(GOLD_DIM_END_MS-GOLD_DIM_START_MS));
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
function chooseTealStart(){const r=Math.random();if(r<TEAL_RELEASE.immediateShare)return rand(0,28);if(r<TEAL_RELEASE.earlyShare)return rand(28,TEAL_RELEASE.earlyEnd);if(r<TEAL_RELEASE.midShare)return rand(TEAL_RELEASE.earlyEnd,TEAL_RELEASE.midEnd);return rand(TEAL_RELEASE.midEnd,SPAWN_CUTOFF_MS);}
function chooseGoldThickness(){const r=Math.random();if(r<.45)return rand(10,15);if(r<.80)return rand(15,20);return rand(20,25);}
function chooseGoldGlowGain(thickness){if(Math.random()<.18)return rand(.9,1.25);if(thickness<13)return rand(3.2,5);if(thickness<17)return rand(2.2,4);if(thickness<21)return rand(1.45,2.7);return rand(1.05,1.8);}
function chooseBloomRepeats(){const r=Math.random();return r<.06?3:r<.24?2:1;}
function makeBloomTiming(){const peak=rand(GOLD_BLOOM_WINDOW_START_MS+70,GOLD_BLOOM_WINDOW_END_MS-70),rise=rand(50,82),fall=rand(54,88);return{bloomStart:Math.max(GOLD_BLOOM_WINDOW_START_MS,peak-rise),bloomPeak:peak,bloomEnd:Math.min(GOLD_BLOOM_WINDOW_END_MS,peak+fall)};}
function setLateHeroTiming(item,slot){const start=slot===0?rand(1740,1810):rand(1870,1920),peak=Math.min(start+rand(80,115),slot===0?1945:2005),end=Math.min(peak+rand(75,105),GOLD_BLOOM_WINDOW_END_MS);item.bloomStart=start;item.bloomPeak=peak;item.bloomEnd=end;}

const tealLayer=document.createElement('div');tealLayer.className='entry-teal-layer';tealLayer.setAttribute('aria-hidden','true');
const mask=document.createElement('canvas');mask.className='entry-mask-canvas';mask.setAttribute('aria-hidden','true');
const fx=document.createElement('canvas');fx.className='entry-fx-canvas';fx.setAttribute('aria-hidden','true');
overlay.append(tealLayer,mask,fx);
const mctx=mask.getContext('2d',{alpha:true}),fctx=fx.getContext('2d',{alpha:true});if(!mctx||!fctx){finishImmediately();return;}

let cssW=1,cssH=1,dpr=1,start=0,raf=0,watchdog=0,finished=false;
let tealEvents=[],goldEvents=[],tealSprites=null,goldSprites=null,goldExposureSprite=null,coverageRemaining=0;
let initialViewportW=0,initialViewportH=0,hiddenAt=0,lastElapsed=0;
const opaqueEraseQueue=[],alphaEraseQueue=[];

function resizeCanvas(c,ctx){c.width=Math.max(1,Math.round(cssW*dpr));c.height=Math.max(1,Math.round(cssH*dpr));c.style.width=`${cssW}px`;c.style.height=`${cssH}px`;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;}
function chooseCanvasDpr(){const device=Math.min(window.devicePixelRatio||1,MAX_DPR),budget=Math.sqrt(MAX_CANVAS_PIXELS/Math.max(1,cssW*cssH));return Math.max(1,Math.min(device,budget));}
function chooseSpeedVwPerMs(){const r=Math.random();if(r<.22)return rand(.015,.023);if(r<.92)return rand(.009,.015);return rand(.006,.009);}
function chooseFamilyKey(){const r=Math.random();return r<.42?'dark':r<.84?'green':'bright';}

function makeOffscreen(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
function buildTealSprite(rgb,variant){const c=makeOffscreen(512,72),ctx=c.getContext('2d',{alpha:true});const y=c.height/2;const grad=ctx.createLinearGradient(0,0,c.width,0);grad.addColorStop(0,`rgba(${rgb},0)`);grad.addColorStop(.018,`rgba(${rgb},.48)`);grad.addColorStop(.08,`rgba(${rgb},.68)`);grad.addColorStop(.90,`rgba(${rgb},.78)`);grad.addColorStop(.975,'rgba(99,213,208,.92)');grad.addColorStop(1,'rgba(237,247,248,1)');ctx.lineCap='butt';ctx.strokeStyle=grad;ctx.shadowColor=`rgb(${rgb})`;ctx.globalAlpha=.34+variant*.08;ctx.shadowBlur=14+variant*5;ctx.lineWidth=13+variant*3;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke();ctx.globalAlpha=.58+variant*.08;ctx.shadowBlur=6+variant*2;ctx.lineWidth=6+variant*1.5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke();ctx.shadowBlur=0;ctx.globalAlpha=.96;ctx.lineWidth=2.2;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke();ctx.fillStyle='rgba(237,247,248,.96)';ctx.fillRect(c.width-4,y-1.2,4,2.4);return c;}
function buildTealSprites(){return{dark:[0,1,2].map(v=>buildTealSprite('11,77,80',v)),green:[0,1,2].map(v=>buildTealSprite('26,127,119',v)),bright:[0,1,2].map(v=>buildTealSprite('99,213,208',v))};}
function buildGoldSprite(kind){const w=512,h=128,padX=80,c=makeOffscreen(w,h),ctx=c.getContext('2d',{alpha:true}),y=h/2,x0=padX,x1=w-padX;const plateau=kind===0?.18:kind===1?.30:.42,inner=kind===0?.10:kind===1?.18:.28;const horizontal=ctx.createLinearGradient(x0,0,x1,0);horizontal.addColorStop(0,'rgba(216,184,106,0)');horizontal.addColorStop(.12,'rgba(216,184,106,.035)');horizontal.addColorStop(.5-plateau,'rgba(216,184,106,.20)');horizontal.addColorStop(.5-inner,'rgba(255,220,132,.62)');horizontal.addColorStop(.5-inner*.45,'rgba(255,240,176,.92)');horizontal.addColorStop(.5+inner*.45,'rgba(255,240,176,.92)');horizontal.addColorStop(.5+inner,'rgba(255,220,132,.62)');horizontal.addColorStop(.5+plateau,'rgba(216,184,106,.20)');horizontal.addColorStop(.88,'rgba(216,184,106,.035)');horizontal.addColorStop(1,'rgba(216,184,106,0)');ctx.fillStyle=horizontal;ctx.fillRect(x0,0,x1-x0,h);const vertical=ctx.createLinearGradient(0,0,0,h);vertical.addColorStop(0,'rgba(255,255,255,0)');vertical.addColorStop(.18,'rgba(255,255,255,.04)');vertical.addColorStop(.34,'rgba(255,255,255,.32)');vertical.addColorStop(.44,'rgba(255,255,255,.82)');vertical.addColorStop(.50,'rgba(255,255,255,1)');vertical.addColorStop(.56,'rgba(255,255,255,.82)');vertical.addColorStop(.66,'rgba(255,255,255,.32)');vertical.addColorStop(.82,'rgba(255,255,255,.04)');vertical.addColorStop(1,'rgba(255,255,255,0)');ctx.globalCompositeOperation='destination-in';ctx.fillStyle=vertical;ctx.fillRect(x0,0,x1-x0,h);ctx.globalCompositeOperation='lighter';ctx.lineCap='round';ctx.strokeStyle=horizontal;ctx.globalAlpha=.78;ctx.lineWidth=5.2;ctx.beginPath();ctx.moveTo(x0,y);ctx.lineTo(x1,y);ctx.stroke();ctx.globalAlpha=.96;ctx.lineWidth=1.35;ctx.beginPath();ctx.moveTo(x0,y);ctx.lineTo(x1,y);ctx.stroke();ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;return c;}
function buildGoldSprites(){return[buildGoldSprite(0),buildGoldSprite(1),buildGoldSprite(2)];}
function buildGoldExposureSprite(){const w=512,h=96,padX=78,c=makeOffscreen(w,h),ctx=c.getContext('2d',{alpha:true}),x0=padX,x1=w-padX;const horizontal=ctx.createLinearGradient(x0,0,x1,0);horizontal.addColorStop(0,'rgba(232,174,42,0)');horizontal.addColorStop(.12,'rgba(232,174,42,.08)');horizontal.addColorStop(.30,'rgba(236,175,38,.34)');horizontal.addColorStop(.44,'rgba(244,185,48,.74)');horizontal.addColorStop(.50,'rgba(255,203,72,.94)');horizontal.addColorStop(.56,'rgba(244,185,48,.74)');horizontal.addColorStop(.70,'rgba(236,175,38,.34)');horizontal.addColorStop(.88,'rgba(232,174,42,.08)');horizontal.addColorStop(1,'rgba(232,174,42,0)');ctx.fillStyle=horizontal;ctx.fillRect(x0,0,x1-x0,h);const vertical=ctx.createLinearGradient(0,0,0,h);vertical.addColorStop(0,'rgba(255,255,255,0)');vertical.addColorStop(.22,'rgba(255,255,255,.05)');vertical.addColorStop(.38,'rgba(255,255,255,.42)');vertical.addColorStop(.47,'rgba(255,255,255,.90)');vertical.addColorStop(.50,'rgba(255,255,255,1)');vertical.addColorStop(.53,'rgba(255,255,255,.90)');vertical.addColorStop(.62,'rgba(255,255,255,.42)');vertical.addColorStop(.78,'rgba(255,255,255,.05)');vertical.addColorStop(1,'rgba(255,255,255,0)');ctx.globalCompositeOperation='destination-in';ctx.fillStyle=vertical;ctx.fillRect(x0,0,x1-x0,h);ctx.globalCompositeOperation='source-over';return c;}

function makeParticle(o={}){const thickness=o.thickness??(Math.random()<.84?rand(.55,2.1):rand(2.1,3)),speedVwMs=o.speedVwMs??chooseSpeedVwPerMs(),coverage=!!o.coverage;if(coverage)coverageRemaining++;return{y:o.y??rand(.5,Math.max(1,cssH-.5)),thickness,headLen:o.headLen??rand(2.5,13),tracerLen:o.tracerLen??rand(2.6,3.6)*cssW,dir:o.dir??(Math.random()<.5?1:-1),start:o.start??chooseTealStart(),speedPxMs:speedVwMs*cssW,preRollMs:o.preRollMs??rand(40,140),familyKey:chooseFamilyKey(),intensity:o.intensity??rand(.52,1),spriteVariant:o.spriteVariant??Math.floor(rand(0,3)),glowScale:o.glowScale??rand(.75,1.35),eraseWidth:o.eraseWidth??Math.max(1,thickness*rand(.95,1.6)),coverage,coveragePass:o.coveragePass??0,coverageTop:o.coverageTop??null,coverageHeight:o.coverageHeight??null,completed:false};}
function makeCoverageStrips(overlap=1.2){const stripH=clamp(cssH/96,3.5,8),strips=[];for(let top=0;top<cssH;top+=stripH){const rawHeight=Math.min(stripH+overlap,cssH-top),coverageTop=Math.max(0,top-overlap*.5),coverageBottom=Math.min(cssH,top+rawHeight+overlap*.5),coverageHeight=Math.max(0,coverageBottom-coverageTop);strips.push({top:coverageTop,height:coverageHeight,y:clamp(top+stripH*.5+rand(-stripH*.16,stripH*.16),.5,cssH-.5)});}return strips;}
function buildPrimaryCoveragePass(){const strips=shuffle(makeCoverageStrips(1.2));let cursor=0,clusterIndex=0;const clusterTotal=Math.ceil(strips.length/7);while(cursor<strips.length){const remaining=strips.length-cursor,members=Math.min(remaining,Math.round(rand(4,9))),progress=clusterTotal<=1?0:clusterIndex/Math.max(1,clusterTotal-1),releaseCurve=Math.pow(progress,.82),baseStart=releaseCurve*1260+rand(-45,75),baseSpeed=rand(.0115,.0175),baseDir=Math.random()<.5?1:-1,basePreRoll=rand(55,125);for(let j=0;j<members;j++){const s=strips[cursor+j],dir=Math.random()<.84?baseDir:-baseDir;tealEvents.push(makeParticle({y:s.y,dir:start=clamp(baseStart+rand(-45,85),0,1360)}));}}
})();